#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
  (
    sed -i 's/ubuntu_theme/cloudbase_theme/g' /etc/openstack-dashboard/local_settings.py
    sed -i 's/Ubuntu theme/Cloudbase theme/g' /etc/openstack-dashboard/local_settings.py
    cd /usr/share/openstack-dashboard
    echo "Collecting and compressing static assets..."
    rm -rf /usr/share/openstack-dashboard/static/custom/* || :
    python manage.py collectstatic --noinput 2>&1 > /dev/null
    python manage.py compress --force 2>&1 > /dev/null
  )

  if [ -x "`which invoke-rc.d 2>/dev/null`" -a -x "/etc/init.d/apache2" ] ; then
    invoke-rc.d --quiet apache2 reload
  fi
fi
