#!/bin/sh
# Copyright 2016-2018 Cloudbase Solutions Srl
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

set -e

locals_file=/etc/openstack-dashboard/local_settings.py

case "$1" in
    remove)
        if [ -f /usr/share/openstack-dashboard/manage.py ]; then
            (
              echo "Removing the Cloudbase Theme configuration ..."
              sed -i '/# Cloudbase/,/^$/d' "$locals_file"
              sed -i 's/cloudbase/ubuntu/g' "$locals_file"
              cd /usr/share/openstack-dashboard
              echo "Collecting and compressing static assets ..."
              rm -rf /var/lib/openstack-dashboard/static/ || :
              python manage.py collectstatic --noinput 2>&1 > /dev/null
              python manage.py compress --force 2>&1 > /dev/null
            )
        fi

        if [ -x "`which invoke-rc.d 2>/dev/null`" -a -x "/etc/init.d/apache2" ] ; then
            invoke-rc.d --quiet apache2 reload
        fi
        ;;
    *)
        ;;
esac

exit 0
